### ISSUE TITLE
How do I convince our CEO to allow us to use grey text?

### ISSUE THREAD

**Issue by luckyhipolito** [specfm/design-details#422]
I'm a UI/UX designer working for a startup with a very intelligent and hands on CEO. 

The problem is that he absolutely hates using light greys. We've had plenty of back and forth about this. He recently convinced our Head of Design to change ALL the text colour to #303440. If he would have it 100% his way, he would use #000000 for everything. I'm all for accessibility, but I don't think that means we should turn every text in to one dark colour.

Our products can be very text heavy, and I just want to be able to show distinction and hierarchy without only relying on font-size or font-weight which is not always applicable. I think he thinks everything should be visible all at once. 

I think he thinks as designers, we like light greys because we just want everything to look pretty. The line he always says is "the most common people don't have the same fancy designer monitors as you guys do". I don't know if he realizes that we're using it as a tool to help the user's eyes be able to distinguish things quicker and easier, and for it to overall feel lighter and less cluttered. I think he's scared people won't see it or be able to read it if it's lighter than #303440. We previously used #535766 for body text and we could use #303440 if we needed a darker colour. But ever since our Head of Design finally backed down and "compromised" again we now use #303440 for every single text we have. 

I don't mind much on what base colour we decide to go with. The only thing I care about is to be able to use a lighter grey than the base grey. The goal for me is that when applicable, I would love to be able to use something like #9096A6 along side the #303440 we have now.

Unfortunately, I'm not the best at explaining and I tend to forget my points and blank out when I have to convince him about these things. Also even if we use big companies as an example such as Stripe (which he loves), he still isn't convinced.

**Sidenote:** We're currently a 60+ company that'll be 80 by this December. There are currently only two designers in the company, the Head of Design, and me. We're currently hiring for another designer to join us. But you can probably tell by this that it's really only up to me to find a way to convince him.

Desperate for help~  Any suggestions/advice/points would be greatly appreciated!!

**Comment by brianlovin** [comment]
Hey @luckyhipolito - great questions. I think off the bat your hunch is right: color can be used to communicate hierarchy and help users focus on the most important pieces of content on a screen, or otherwise make a text-heavy screen more scannable.

That being said, the CEO's concerns about legibility and contrast are also valid. Some monitors really struggle to clearly render lighter text. I ran a quick check and the #9096A6 hex fails contrast checks at all levels, so I think that's worth considering. I would recommend aiming for 4.5:1 minimum contrast on text, unless it's large/bold text in which case you can get away with 3:1 (AA+).

My recommendation is to move out of opinion land and into data/user land. Start talking to customers and showing them variants. Record their comments and answers, see if they are able to navigate more easily or scan pages more quickly. Data wins arguments, in this case, I think.

**Comment by luckyhipolito** [comment]
Thank you so much Brian! I think I'll try that out~

**Comment by brianlovin** [comment]
Discussed further in The Sidebar of today's episode! https://designdetails.fm/episodes/9paNsXR0
